//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteEscuela.EscuelaCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sw.model/", ConfigurationName="EscuelaCliente.SWEscuela")]
    public interface SWEscuela {
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteEscuela.EscuelaCliente.listarEscuelaResponse listarEscuela(ClienteEscuela.EscuelaCliente.listarEscuelaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteEscuela.EscuelaCliente.listarEscuelaResponse> listarEscuelaAsync(ClienteEscuela.EscuelaCliente.listarEscuelaRequest request);
        
        // CODEGEN: O parâmetro 'arg0' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void addEscuela(ClienteEscuela.EscuelaCliente.addEscuela request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task addEscuelaAsync(ClienteEscuela.EscuelaCliente.addEscuela request);
        
        // CODEGEN: O parâmetro 'arg0' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void addEscuelaNET(ClienteEscuela.EscuelaCliente.addEscuelaNET request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task addEscuelaNETAsync(ClienteEscuela.EscuelaCliente.addEscuelaNET request);
        
        // CODEGEN: O parâmetro 'arg0' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarEscuela(ClienteEscuela.EscuelaCliente.eliminarEscuela request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task eliminarEscuelaAsync(ClienteEscuela.EscuelaCliente.eliminarEscuela request);
        
        // CODEGEN: O parâmetro 'arg0' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void editarSW(ClienteEscuela.EscuelaCliente.editarSW request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task editarSWAsync(ClienteEscuela.EscuelaCliente.editarSW request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteEscuela.EscuelaCliente.buscarSWResponse buscarSW(ClienteEscuela.EscuelaCliente.buscarSWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteEscuela.EscuelaCliente.buscarSWResponse> buscarSWAsync(ClienteEscuela.EscuelaCliente.buscarSWRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.model/")]
    public partial class escuela : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estudianteField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private string idEField;
        
        private string nombreField;
        
        private string profesorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estudiante {
            get {
                return this.estudianteField;
            }
            set {
                this.estudianteField = value;
                this.RaisePropertyChanged("estudiante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idE {
            get {
                return this.idEField;
            }
            set {
                this.idEField = value;
                this.RaisePropertyChanged("idE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string profesor {
            get {
                return this.profesorField;
            }
            set {
                this.profesorField = value;
                this.RaisePropertyChanged("profesor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEscuela", WrapperNamespace="http://sw.model/", IsWrapped=true)]
    public partial class listarEscuelaRequest {
        
        public listarEscuelaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEscuelaResponse", WrapperNamespace="http://sw.model/", IsWrapped=true)]
    public partial class listarEscuelaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteEscuela.EscuelaCliente.escuela[] @return;
        
        public listarEscuelaResponse() {
        }
        
        public listarEscuelaResponse(ClienteEscuela.EscuelaCliente.escuela[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addEscuela", WrapperNamespace="http://sw.model/", IsWrapped=true)]
    public partial class addEscuela {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        public addEscuela() {
        }
        
        public addEscuela(string arg0, string arg1, string arg2, System.DateTime arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addEscuelaNET", WrapperNamespace="http://sw.model/", IsWrapped=true)]
    public partial class addEscuelaNET {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteEscuela.EscuelaCliente.escuela arg0;
        
        public addEscuelaNET() {
        }
        
        public addEscuelaNET(ClienteEscuela.EscuelaCliente.escuela arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEscuela", WrapperNamespace="http://sw.model/", IsWrapped=true)]
    public partial class eliminarEscuela {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public eliminarEscuela() {
        }
        
        public eliminarEscuela(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editarSW", WrapperNamespace="http://sw.model/", IsWrapped=true)]
    public partial class editarSW {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg4;
        
        public editarSW() {
        }
        
        public editarSW(string arg0, string arg1, string arg2, string arg3, System.DateTime arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarSW", WrapperNamespace="http://sw.model/", IsWrapped=true)]
    public partial class buscarSWRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public buscarSWRequest() {
        }
        
        public buscarSWRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarSWResponse", WrapperNamespace="http://sw.model/", IsWrapped=true)]
    public partial class buscarSWResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.model/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteEscuela.EscuelaCliente.escuela @return;
        
        public buscarSWResponse() {
        }
        
        public buscarSWResponse(ClienteEscuela.EscuelaCliente.escuela @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SWEscuelaChannel : ClienteEscuela.EscuelaCliente.SWEscuela, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWEscuelaClient : System.ServiceModel.ClientBase<ClienteEscuela.EscuelaCliente.SWEscuela>, ClienteEscuela.EscuelaCliente.SWEscuela {
        
        public SWEscuelaClient() {
        }
        
        public SWEscuelaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWEscuelaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWEscuelaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWEscuelaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEscuela.EscuelaCliente.listarEscuelaResponse ClienteEscuela.EscuelaCliente.SWEscuela.listarEscuela(ClienteEscuela.EscuelaCliente.listarEscuelaRequest request) {
            return base.Channel.listarEscuela(request);
        }
        
        public ClienteEscuela.EscuelaCliente.escuela[] listarEscuela() {
            ClienteEscuela.EscuelaCliente.listarEscuelaRequest inValue = new ClienteEscuela.EscuelaCliente.listarEscuelaRequest();
            ClienteEscuela.EscuelaCliente.listarEscuelaResponse retVal = ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).listarEscuela(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteEscuela.EscuelaCliente.listarEscuelaResponse> ClienteEscuela.EscuelaCliente.SWEscuela.listarEscuelaAsync(ClienteEscuela.EscuelaCliente.listarEscuelaRequest request) {
            return base.Channel.listarEscuelaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteEscuela.EscuelaCliente.listarEscuelaResponse> listarEscuelaAsync() {
            ClienteEscuela.EscuelaCliente.listarEscuelaRequest inValue = new ClienteEscuela.EscuelaCliente.listarEscuelaRequest();
            return ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).listarEscuelaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ClienteEscuela.EscuelaCliente.SWEscuela.addEscuela(ClienteEscuela.EscuelaCliente.addEscuela request) {
            base.Channel.addEscuela(request);
        }
        
        public void addEscuela(string arg0, string arg1, string arg2, System.DateTime arg3, string arg4) {
            ClienteEscuela.EscuelaCliente.addEscuela inValue = new ClienteEscuela.EscuelaCliente.addEscuela();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).addEscuela(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ClienteEscuela.EscuelaCliente.SWEscuela.addEscuelaAsync(ClienteEscuela.EscuelaCliente.addEscuela request) {
            return base.Channel.addEscuelaAsync(request);
        }
        
        public System.Threading.Tasks.Task addEscuelaAsync(string arg0, string arg1, string arg2, System.DateTime arg3, string arg4) {
            ClienteEscuela.EscuelaCliente.addEscuela inValue = new ClienteEscuela.EscuelaCliente.addEscuela();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).addEscuelaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ClienteEscuela.EscuelaCliente.SWEscuela.addEscuelaNET(ClienteEscuela.EscuelaCliente.addEscuelaNET request) {
            base.Channel.addEscuelaNET(request);
        }
        
        public void addEscuelaNET(ClienteEscuela.EscuelaCliente.escuela arg0) {
            ClienteEscuela.EscuelaCliente.addEscuelaNET inValue = new ClienteEscuela.EscuelaCliente.addEscuelaNET();
            inValue.arg0 = arg0;
            ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).addEscuelaNET(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ClienteEscuela.EscuelaCliente.SWEscuela.addEscuelaNETAsync(ClienteEscuela.EscuelaCliente.addEscuelaNET request) {
            return base.Channel.addEscuelaNETAsync(request);
        }
        
        public System.Threading.Tasks.Task addEscuelaNETAsync(ClienteEscuela.EscuelaCliente.escuela arg0) {
            ClienteEscuela.EscuelaCliente.addEscuelaNET inValue = new ClienteEscuela.EscuelaCliente.addEscuelaNET();
            inValue.arg0 = arg0;
            return ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).addEscuelaNETAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ClienteEscuela.EscuelaCliente.SWEscuela.eliminarEscuela(ClienteEscuela.EscuelaCliente.eliminarEscuela request) {
            base.Channel.eliminarEscuela(request);
        }
        
        public void eliminarEscuela(string arg0) {
            ClienteEscuela.EscuelaCliente.eliminarEscuela inValue = new ClienteEscuela.EscuelaCliente.eliminarEscuela();
            inValue.arg0 = arg0;
            ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).eliminarEscuela(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ClienteEscuela.EscuelaCliente.SWEscuela.eliminarEscuelaAsync(ClienteEscuela.EscuelaCliente.eliminarEscuela request) {
            return base.Channel.eliminarEscuelaAsync(request);
        }
        
        public System.Threading.Tasks.Task eliminarEscuelaAsync(string arg0) {
            ClienteEscuela.EscuelaCliente.eliminarEscuela inValue = new ClienteEscuela.EscuelaCliente.eliminarEscuela();
            inValue.arg0 = arg0;
            return ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).eliminarEscuelaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ClienteEscuela.EscuelaCliente.SWEscuela.editarSW(ClienteEscuela.EscuelaCliente.editarSW request) {
            base.Channel.editarSW(request);
        }
        
        public void editarSW(string arg0, string arg1, string arg2, string arg3, System.DateTime arg4) {
            ClienteEscuela.EscuelaCliente.editarSW inValue = new ClienteEscuela.EscuelaCliente.editarSW();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).editarSW(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ClienteEscuela.EscuelaCliente.SWEscuela.editarSWAsync(ClienteEscuela.EscuelaCliente.editarSW request) {
            return base.Channel.editarSWAsync(request);
        }
        
        public System.Threading.Tasks.Task editarSWAsync(string arg0, string arg1, string arg2, string arg3, System.DateTime arg4) {
            ClienteEscuela.EscuelaCliente.editarSW inValue = new ClienteEscuela.EscuelaCliente.editarSW();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).editarSWAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEscuela.EscuelaCliente.buscarSWResponse ClienteEscuela.EscuelaCliente.SWEscuela.buscarSW(ClienteEscuela.EscuelaCliente.buscarSWRequest request) {
            return base.Channel.buscarSW(request);
        }
        
        public ClienteEscuela.EscuelaCliente.escuela buscarSW(string arg0) {
            ClienteEscuela.EscuelaCliente.buscarSWRequest inValue = new ClienteEscuela.EscuelaCliente.buscarSWRequest();
            inValue.arg0 = arg0;
            ClienteEscuela.EscuelaCliente.buscarSWResponse retVal = ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).buscarSW(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteEscuela.EscuelaCliente.buscarSWResponse> ClienteEscuela.EscuelaCliente.SWEscuela.buscarSWAsync(ClienteEscuela.EscuelaCliente.buscarSWRequest request) {
            return base.Channel.buscarSWAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteEscuela.EscuelaCliente.buscarSWResponse> buscarSWAsync(string arg0) {
            ClienteEscuela.EscuelaCliente.buscarSWRequest inValue = new ClienteEscuela.EscuelaCliente.buscarSWRequest();
            inValue.arg0 = arg0;
            return ((ClienteEscuela.EscuelaCliente.SWEscuela)(this)).buscarSWAsync(inValue);
        }
    }
}
